#Splunk Connect for Syslog (SC4S) by Splunk, Inc.
#
#To the extent possible under law, the person who associated CC0 with
#Splunk Connect for Syslog (SC4S) has waived all copyright and related or neighboring rights
#to Splunk Connect for Syslog (SC4S).
#
#You should have received a copy of the CC0 legalcode along with this
#work.  If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
version: "3.7"
services:
  test:
    build:
      context: .
    links:
      - splunk
    volumes:
      - results:/work/test-results

  splunk:
    build:
      context: tests
      args:
        SPLUNK_APP: TA_fiction
        SPLUNK_VERSION: ${SPLUNK_VERSION}
    ports:
      - "8000"
      - "8088"
      - "8089"
      - "9997"
    environment:
      - SPLUNK_PASSWORD=Changed@11
      - SPLUNK_HEC_TOKEN=${SPLUNK_HEC_TOKEN}
      - SPLUNK_START_ARGS=--accept-license
volumes:
  results:
    external: false
