ARG SPLUNK_VERSION=latest
FROM splunk/splunk:$SPLUNK_VERSION
ARG SPLUNK_VERSION=latest
ARG SPLUNK_APP=TA_UNKNOWN
ARG SOURCE_PACKAGE=package
RUN echo ${SPLUNK_VERSION} $SOURCE_PACKAGE
COPY tests/addons /opt/splunk/etc/apps/
COPY deps/apps /opt/splunk/etc/apps/
