#Splunk Connect for Syslog (SC4S) by Splunk, Inc.
#
#To the extent possible under law, the person who associated CC0 with
#Splunk Connect for Syslog (SC4S) has waived all copyright and related or neighboring rights
#to Splunk Connect for Syslog (SC4S).
#
#You should have received a copy of the CC0 legalcode along with this
#work.  If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
FROM ubuntu

RUN mkdir -p /work/tests
RUN mkdir -p /work/test-results/functional

COPY entrypoint.sh /

COPY . /work

RUN export DEBIAN_FRONTEND=noninteractive ;\
    apt-get update ;\
    apt-get install -y --no-install-recommends apt-utils ;\
    apt-get install -y locales ;\
    localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 ;\
    apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl git 

ENV LANG en_US.utf8

COPY pytest-ci.ini /work/pytest.ini
COPY tests /work/tests/
WORKDIR /work

ENTRYPOINT "/entrypoint.sh"
CMD tests