#Splunk Connect for Syslog (SC4S) by Splunk, Inc.
#
#To the extent possible under law, the person who associated CC0 with
#Splunk Connect for Syslog (SC4S) has waived all copyright and related or neighboring rights
#to Splunk Connect for Syslog (SC4S).
#
#You should have received a copy of the CC0 legalcode along with this
#work.  If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
FROM python:3.7.9

RUN mkdir -p /work/tests
RUN mkdir -p /work/test-results/functional

COPY entrypoint.sh /
RUN apt-get update ; apt-get install -y curl wget git; apt-get clean

RUN pip install --upgrade setuptools pip;\
    curl https://pyenv.run | bash;\
    curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python

COPY . /work
COPY pytest-ci.ini /work/pytest.ini
WORKDIR /work
RUN cd /work;~/.poetry/bin/poetry config virtualenvs.create false;~/.poetry/bin/poetry build;~/.poetry/bin/poetry install

ENTRYPOINT "/entrypoint.sh"
CMD tests