apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: uf
  name: splunk-uf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uf
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app: uf
    spec:
      initContainers:
      - name: copy-addon-to-container
        image: ubuntu:latest
        command:
        - /bin/sh
        args:
        - -c
        - |
          ls -al;
          ls -al /addon/;
          tar -xzf /addon/$SPLUNK_ADDON.tgz $SPLUNK_ADDON;
          cp -r $SPLUNK_ADDON /ufaddon/;
          ls -al /ufaddon/;
        volumeMounts:
        - mountPath: /addon
          name: addon
        - mountPath: /ufaddon
          name: ufaddon
      containers:
      - name: uf
        env:
        - name: SPLUNKBASE_USERNAME
          value: admin
        - name: SPLUNK_PASSWORD
          value: Chang3d!
        - name: SPLUNK_START_ARGS
          value: --accept-license
        image: splunk/universalforwarder:latest
        ports:
        - containerPort: 8089
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - cat /opt/container_artifact/ansible.log | grep "PLAY RECAP"
          failureThreshold: 15
          initialDelaySeconds: 30
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: 750m
            memory: 4Gi
        volumeMounts:
        - mountPath: /opt/splunkforwarder/etc/apps/
          name: ufaddon
      volumes:
      - hostPath:
          path: /
          type: Directory
        name: addon
      - emptyDir: {}
        name: ufaddon
