apiVersion: enterprise.splunk.com/v1
kind: Standalone
metadata:
  name: s1
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  defaults: |-
    splunk:
      apps_location:
        - http://nginx/$SPLUNK_ADDON.tgz
        - http://nginx/indexes.tgz
  licenseUrl: http://nginx/enterprise.lic