name: Python Code Quality and Lint

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Python Code Quality and Lint
      uses: ricardochaves/python-lint@v1.1.0
      with:
        python-root-list: "pytest_splunk_addon tests"
        use-pylint: false
        use-pycodestyle: false
        use-flake8: true
        use-black: true
        use-mypy: false
        use-isort: true
        extra-pylint-options: ""
        extra-pycodestyle-options: ""
        extra-flake8-options: ""
        extra-black-options: ""
        extra-mypy-options: ""
        extra-isort-options: ""